# Generated by Django 2.2.6 on 2019-10-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='media_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
